### ISSUE TITLE
[BUG] - Plutus script uses same UTxO for fees and collateral

### ISSUE THREAD

**Issue by tdiesler** [IntersectMBO/cardano-node#3295]
**Internal/External**
*External*   otherwise.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**

Node version: 1.30.1

This screenshot shows a mint Tx that uses the same UTxO for fees and collateral. Is this allowed?

![image](https://user-images.githubusercontent.com/244946/137355057-b8257826-0ee7-4c78-aed7-c2ab13f0fbbc.png)

**Comment by grim-i-am** [comment]
My understanding is that if the transaction succeeds, then the fee is taken. If the transaction fails because of a script error, the collateral is taken and the fee is not. So it would make sense that the same UTxO is allowed.

On the other hand, if the transaction fails, the full amount of the collateral UTxO is lost so it's a good idea to have a dedicated collateral UTxO with a small amount of Ada.
