### ISSUE TITLE
[BUG] - `query leadership-chedule` reports wrong slots on Babbage

### ISSUE THREAD

**Issue by mkoura** [IntersectMBO/cardano-node#4017]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
The slots reported by `query leadership-schedule` on Babbage are not correct. In the given epoch the pool forged 40 blocks at following slots: 385112, 385144, 385164, 385177, 385213, 385280, 385294, 385309, 385357, 385396, 385439, 385477, 385508, 385511, 385520, 385524, 385527, 385616, 385620, 385654, 385657, 385665, 385724, 385726, 385771, 385799, 385856, 385867, 385883, 385909, 385910, 385915, 385945, 386000, 386020, 386024, 386032, 386061, 386079, 386092
The slots were confirmed by db-sync and node log messages. The total number of blocks was also checked in ledger state dump.

The `query leadership-schedule` reported 28 slots: 385107, 385131, 385173, 385214, 385318, 385322, 385438, 385447, 385450, 385463, 385472, 385492, 385493, 385615, 385624, 385741, 385786, 385823, 385826, 385858, 385902, 385941, 385946, 385951, 385978, 385979, 386067, 386088

It work in Alonzo era. It was tested on local Babbage network with 3 block producing pools.

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: 7608488571126a3078528c09243e8db73a9159df

______________

Tasks

- [x] https://github.com/input-output-hk/cardano-node/pull/4106

**Comment by newhoggy** [comment]
This is the failing test: https://github.com/input-output-hk/cardano-node-tests/blob/f82c17ae0a223dcc7a6ae7a5873c07745f800a34/cardano_node_tests/tests/test_blocks.py#L36-L137

**Comment by nfrisby** [comment]
@newhoggy Am I right that this is the main entrypoint code in question?

https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs#L1130-L1268

**Comment by JaredCorduan** [comment]
yes @nfrisby, that is the entry point

**Comment by CarlosLopezDeLara** [comment]
@mkoura Looks like this is fixed by https://github.com/input-output-hk/cardano-node/pull/4018, correct?

**Comment by nfrisby** [comment]
I think this is the culprit. It's sadly another example of `cardano-node` code that was relying/duplicating TPraos logic. And since Babbage uses Praos instead of TPraos, it's not working.

https://github.com/input-output-hk/cardano-node/blob/483e7bff444eb930d16560efe916c798cd051c06/cardano-api/src/Cardano/Api/LedgerState.hs#L1444-L1446

For Babbage, we use Praos, which defines the thing compared to the leadership threshold via:

https://github.com/input-output-hk/ouroboros-network/blob/d78f61c4d720c1eab65eb3edc1a313f58b5134e8/ouroboros-consensus-protocol/src/Ouroboros/Consensus/Protocol/Praos.hs#L395-L397

where

https://github.com/input-output-hk/ouroboros-network/blob/d78f61c4d720c1eab65eb3edc1a313f58b5134e8/ouroboros-consensus-protocol/src/Ouroboros/Consensus/Protocol/Praos/VRF.hs#L54-L69

Shelley-through-Alonzo instead used TPraos, which defines the thing compared to the leadership threshold via:

https://github.com/input-output-hk/ouroboros-network/blob/d78f61c4d720c1eab65eb3edc1a313f58b5134e8/ouroboros-consensus-protocol/src/Ouroboros/Consensus/Protocol/TPraos.hs#L354-L358

-----

I don't know how naive this suggestion is, but would it be possible for you to call into the `checkIsLeader` function in the Consensus API instead of duplicating its logic? I don't know how much trouble it is to prepare these arguments, but I'm hoping it'd be less error-prone than maintaining the two copies of the leader check logic.

https://github.com/input-output-hk/ouroboros-network/blob/1f6433d0d2e17511a17df7ee9b76be9df74887d2/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/Abstract.hs#L126-L132

**Comment by JaredCorduan** [comment]
I should have realized that when I looked at the entry point 🤦. great catch @nfrisby !

**Comment by Jimbo4350** [comment]
This should be fixed by #4106. @newhoggy are both the `--next` and `--current` leadership schedules working? CC: @mkoura

**Comment by os11k** [comment]
Doesn't work for me on Testnet & Vasil-Testnet. I'm getting wrong slots. For both `--next` & `--current`. Next I compared with CNCLI, what seems returns correct values.

**Comment by os11k** [comment]
Yes, seems to work correctly  for both `--next` & `--current`. Tested on Vasil-testnet with master.
