### ISSUE TITLE
[BUG] - 9.1.0 cardano node slow start

### ISSUE THREAD

**Issue by adavault** [IntersectMBO/cardano-node#5929]
**External**
*Internal*   if an IOHK staff member.
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Cardano node 8.9.4 took approx 3 mins to start. After upgrade to 9.1.0 it now takes around 60 mins on equivalent setup.

**Steps to reproduce**
1. Upgrade to 9.1.0
2. Allow node to convert existing ledger (approx 5 hours)
3. Allow to operate normally for 24 hours in case node needs to checkpoint ledger
4. Restart node using systemctl stop cnode...
5. Node takes approx 60 mins to start

**Expected behavior**
Node restarts in minutes as before

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version cardano-node 9.1.0 - linux-x86_64 - ghc-8.10
git rev 176f99e51155cb3eaa0711db1c3c969d67438958
- CLI version  cardano-cli 9.2.1.0 - linux-x86_64 - ghc-8.10
git rev 176f99e51155cb3eaa0711db1c3c969d67438958

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

Logs show a lot of this:
`{"app":[],"at":"2024-07-29T18:35:45.82Z","data":{"finalChunk":"6049","initialChunk":"2811","kind":"TraceImmutableDBEvent.StartedValidatingChunk"},"env":"9.1.0:176f9","host":"xxx","loc":null,"msg":"","ns":["cardano.node.ChainDB"],"pid":"801","sev":"Info","thread":"9"}`

On the previous slow startup that was tested 24 hours before there were 6041 chunks to validate.

**Comment by jasagredo** [comment]
A normal shutdown of the node will write a `clean` marker in the database path, so that a subsequent start of the node will "trust" that the previous shutdown did the right thing and only validate the last chunk.

If for whatever reason your node did not shut down gracefully, the `clean` marker will be gone and your node will re-validate the immutable db from genesis which will take quite some time.

There is not much to do here, a 9.0 node that starts with a non-clean database would have taken a similar amount of time, this is not a 9.1 bug.

I'm closing the issue, I hope the explanation above makes sense, if not please ask for further clarification.

**Comment by adavault** [comment]
Yes, makes sense. Thanks for clarifying. What is strange is the systemd service definition hasn't changed, still sends a SIGINT with the same timings as it did for 8.9.4. Which worked fine as did every version before that from 1.35... I'll look into it some more and try increasing timings (60 seconds)...perhaps that's it.
